# Gopkg.toml for github.com/ulule/sqlxx

ignored = [
  "github.com/stretchr/testify/require",
  "github.com/davecgh/go-spew/spew"
]

[metadata]
  codename = "sqlxx"

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/ulule/sqlx"
  revision = "c5252437a47be63a059eccced7436bc68e0e4a53"

[[constraint]]
  name = "github.com/ulule/sqalx"
  revision = "d9cae201d6f9efafb7c8b76038c077c5d203f161"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "90697d60dd844d5ef6ff15135d0203f65d2f53b8"

[[constraint]]
  name = "github.com/serenize/snaker"
  revision = "a683aaf2d516deecd70cad0c72e3ca773ecfcef0"

[[constraint]]
  name = "github.com/ulule/loukoum"
  revision = "79401924b612bdf526ab9e1b55483103ec4429fc"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/oklog/ulid"
  revision = "3928b679b154aad7ea1db5352e4277e4e448b324"
